# Generated by Django 4.0.3 on 2022-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('P', 'Personal'), ('W', 'Work')], max_length=255),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='type',
            field=models.CharField(choices=[('M', 'Mobile'), ('MW', 'Mobile Work'), ('W', 'Work'), ('F', 'Fax'), ('S', 'Skype'), ('AS', 'Answering service')], max_length=255),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='type',
            field=models.CharField(choices=[('S', 'Skype'), ('T', 'Twitter'), ('LI', 'LinkedIn'), ('F', 'Facebook'), ('P', 'Pinterest')], max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='type',
            field=models.CharField(choices=[('W', 'Work'), ('PE', 'Personal'), ('PO', 'Portfolio'), ('Blog', 'Blog')], max_length=255),
        ),
    ]
