# Generated by Django 4.0.3 on 2022-03-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_alter_address_state_alter_email_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
